import { EB_Garamond } from "next/font/google";
import "./globals.css";

const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
});

export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${garamond.variable} antialiased font-base bg-black cursor-default selection:bg-transparent`}
      >
        {children}
      </body>
    </html>
  );
}
